CREATE TABLE if not exists "film"
(
    "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "name"         varchar,
    "description"  varchar,
    "release_date" date,
    "duration"     integer,
    "mpa"          integer
);

CREATE TABLE if not exists "genre"
(
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "name" varchar
);

CREATE TABLE if not exists "mpa"
(
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "name" varchar
);

CREATE TABLE if not exists "films_genres"
(
    "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "film_id"  integer,
    "genre_id" integer
);

CREATE TABLE if not exists "likes"
(
    "id"      INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "user_id" integer,
    "film_id" integer
);

CREATE TABLE if not exists "user"
(
    "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "email"    varchar,
    "login"    varchar,
    "name"     varchar,
    "birthday" date
);

CREATE TABLE if not exists "users_friends"
(
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "user_id"   integer,
    "friend_id" integer,
    "status"    integer
);

CREATE TABLE if not exists "status"
(
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "name" varchar check "name" in ('accepted', 'not accepted')
);

COMMENT ON COLUMN "status"."name" IS 'accepted | not accepted';

ALTER TABLE "films_genres"
    ADD FOREIGN KEY ("film_id") REFERENCES "film" ("id");

ALTER TABLE "films_genres"
    ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");

ALTER TABLE "film"
    ADD FOREIGN KEY ("mpa") REFERENCES "mpa" ("id");

ALTER TABLE "likes"
    ADD FOREIGN KEY ("film_id") REFERENCES "film" ("id");

ALTER TABLE "likes"
    ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "users_friends"
    ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "users_friends"
    ADD FOREIGN KEY ("friend_id") REFERENCES "user" ("id");

ALTER TABLE "users_friends"
    ADD FOREIGN KEY ("status") REFERENCES "status" ("id");
